version: '3.4'
services:
  ai-legacy-frontend:
    build: 
      context: .
      target: development
    ports:
      - '3000:3000'
    env_file:
      - 'compose/aws.env'
    environment:
      PORT: 3000
      NODE_ENV: development
      REDIS_HOST: redis
      LOCALSTACK_ENDPOINT: http://localstack:4566
      USE_SINGLE_INSTANCE_CACHE: true
      API_URL: http://host.docker.internal:3001
    networks:
      - cdp-tenant
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/node/src
        - action: sync
          path: ./package.json
          target: /home/node/package.json
        - action: rebuild
          path: ./package-lock.json

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
